AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  ms-graph-api-connector
  A Typescript API to connect with ms graph for RFE

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ms-graph-connector/
      Handler: app.lambdaHandler
      FunctionUrlConfig:
        AuthType: NONE # Options: AWS_IAM / NONE
        # No Required Cors: YES/NO
        # Optional InvokeMode: BUFFERED / RESPONSE_STREAM he mode that your function URL will be invoked. To have your function return the response after invocation completes, set to BUFFERED
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
