AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  ms-graph-api-connector
  A Typescript API to connect with ms graph for RFE

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    # FUNCTION  RESOURCES OVERRIDE GLOBALS

Resources:
  MsGraphApiConnectorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ms-graph-connector/
      Handler: app.lambdaHandler
      FunctionUrlConfig:
        AuthType: NONE # Options: AWS_IAM / NONE
        # No Required Cors: YES/NO
        # Optional InvokeMode: BUFFERED / RESPONSE_STREAM he mode that your function URL will be invoked. To have your function return the response after invocation completes, set to BUFFERED
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 528
      Environment:
        Variables:
          # EXAMPLE: ONE234
          TENANT_ID: 71124398-4b74-4832-b48a-1c01fb46e497
          CLIENT_ID: a4318a83-8311-407d-b571-768aff5588de'
          CLIENT_SECRET: rid8Q~hZ13OKFa0HgH5ceYdyCzXv5Nm4HR_A-bLr
          AUTH_CODE: 1KaLmZYf8X5TBMb4MvVA5oOUrlwoSG # This is the auth code for the user

    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: "true"
